"""the reply message

Revision ID: e30560fb4e60
Revises: 26a12deebd0e
Create Date: 2025-12-10 16:31:58.628860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e30560fb4e60'
down_revision: Union[str, Sequence[str], None] = '26a12deebd0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('parent_message_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'messages', 'messages', ['parent_message_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_column('messages', 'parent_message_id')
    # ### end Alembic commands ###
